[package]
name = "acme-lib"
version = "0.1.0"
authors = ["Martin Algesten <martin@algesten.se>"]
edition = "2018"

[dependencies]
base64 = "0.10.0"
lazy_static = "1.2.0"
log = "0.4.6"
openssl = "0.10.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = "0.1"
ureq = "0.8.1"

[dev-dependencies]
env_logger = { version = "0.6.0", default-features = false }
futures = "0.1.25"
hyper = "0.12.19"
regex = "1.1.0"
